export const GET_ERRORS = 'GET_ERRORS';
export const GET_MESSAGE_PHONE = 'GET_MESSAGE_PHONE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_LOCATIONCATEGORIES = 'GET_LOCATIONCATEGORIES';
export const CATEGORY_LOADING = 'CATEGORY_LOADING';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const GET_CODE = 'GET_CODE';
export const CODE_LOADING = 'CODE_LOADING';