export const GET_ERRORS = 'GET_ERRORS';
export const GET_MESSAGE_PHONE = 'GET_MESSAGE_PHONE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SEND_PASS_LOADING = 'SEND_PASS_LOADING';

export const GET_LOCATIONCATEGORIES = 'GET_LOCATIONCATEGORIES';
export const CATEGORY_LOADING = 'CATEGORY_LOADING';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const GET_CODE = 'GET_CODE';
export const CODE_LOADING = 'CODE_LOADING';
export const GET_CHECK_CODE_RES = 'GET_CHECK_CODE_RES';
export const CLEAR_MCC = 'CLEAR_MCC';
export const CLEAR_MSC = 'CLEAR_MSC';

export const SET_USER = 'SET_USER';
export const RESET_STATE = 'RESET_STATE';


export const CREATE_PRODUCT = 'CREATE_PRODUCT'
export const GET_PRODUCT_CATEGORIES = 'GET_PRODUCT_CATEGORIES'