export const GET_ERRORS = 'GET_ERRORS';
export const GET_MESSAGE_PHONE = 'GET_MESSAGE_PHONE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SEND_PASS_LOADING = 'SEND_PASS_LOADING';

export const GET_LOCATIONCATEGORIES = 'GET_LOCATIONCATEGORIES';
export const CATEGORY_LOADING = 'CATEGORY_LOADING';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const GET_CODE = 'GET_CODE';
export const PRODUCT_PARENT_CATEGORIES_LOADING = 'PRODUCT_PARENT_CATEGORIES_LOADING';
export const GET_CHECK_CODE_RES = 'GET_CHECK_CODE_RES';
export const CLEAR_MCC = 'CLEAR_MCC';
export const CLEAR_MSC = 'CLEAR_MSC';
export const CODE_LOADING = 'CODE_LOADING';

export const SET_USER = 'SET_USER';
export const RESET_STATE = 'RESET_STATE';

export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const GET_PRODUCT_PARENT_CATEGORIES = 'GET_PRODUCT_PARENT_CATEGORIES';
export const PRODUCT_PRODUCT_BY_USER_ID_LOADING = 'PRODUCT_PRODUCT_BY_USER_ID_LOADING';
export const GET_PRODUCT_BY_USER_ID = 'GET_PRODUCT_BY_USER_ID';
export const CREATE_PRODUCT_PARENT_CATEGORIES = 'CREATE_PRODUCT_PARENT_CATEGORIES';
export const DELETE_PRODUCT_BY_ID = "DELETE_PRODUCT_BY_ID";
export const DELETE_PRODUCT_CATEGORY_BY_ID = "DELETE_PRODUCT_CATEGORY_BY_ID";
export const UPDATE_PRODUCT_BY_ID = "UPDATE_PRODUCT_BY_ID";
export const UPDATE_PRODUCT_CATEGORIES_BY_ID = "UPDATE_PRODUCT_CATEGORIES_BY_ID";

export const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL";

export const GET_PROFILE = "GET_PROFILE";




// FOR ADMIN ROLE
export const GET_ALL_USERS = "GET_ALL_USERS";

export const BAN_USER_BY_ID = "BAN_USER_BY_ID";

export const GET_REPORTS = "GET_REPORTS";