export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const TEST_DISPATCH = 'TEST_DISPATCH';

export const GET_LOCATIONCATEGORIES = 'GET_LOCATIONCATEGORIES';
export const CATEGORY_LOADING = 'CATEGORY_LOADING';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';